### ISSUE TITLE
stylelint --fix is not working when primer rules is enabled

### ISSUE THREAD

**Issue by Grawl** [primer/stylelint-config#318] opened 2023-01-25 04:28 UTC
If I enable `primer/no-unused-vars`, I cannot use `--fix` feature of Stylelint.

If I just disable it, like `"primer/no-unused-vars": false` or remove this line, `--fix` is working again.

**Comment by jonrohan** [comment] 2023-01-25 17:29
Thanks for the report! I'll see if I can track down the cause

**Comment by Grawl** [comment] 2023-01-27 07:43
```
TypeError: Cannot read properties of undefined (reading 'startsWith')
```

**Comment by jonrohan** [comment] 2024-09-26 21:54
Should be fixed in 13.1.0

**Closed by jonrohan** 2024-09-26 21:54 UTC
Labels: bug
